# GitHub Action to deploy all your templates

name: Azure Deployment

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure PowerShell module
        run: Install-Module -Name Az -Force -AllowClobber
      - name: Login to Azure
        run: |
          $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
          }
          $credential = New-Object -TypeName PSCredential -ArgumentList $servicePrincipal.clientId, $(ConvertTo-SecureString -String $servicePrincipal.clientSecret -AsPlainText -Force)

          Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $servicePrincipal.tenantId

      - name: Deploy to Azure
        shell: pwsh
        
        # here you can add all the powershell scripts that you want to run
        # write the absolute paths to your powershell scripts
        run: |
          "<1st script's absolute path>"
          "<2st script's absolute path>"
