name: Azure Deployment

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure PowerShell module
        run: Install-Module -Name Az -Force -AllowClobber
      - name: Login to Azure
        run: |
          $servicePrincipal = @{
          clientId       = "${{ secrets.AZURE_CLIENT_ID }}"
          clientSecret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenantId       = "${{ secrets.AZURE_TENANT_ID }}"
          }
          Connect-AzAccount -ServicePrincipal -Credential $(Get-Credential -TenantId $servicePrincipal.tenantId -ClientId $servicePrincipal.clientId -ClientSecret $servicePrincipal.clientSecret)

      - name: Deploy to Azure
        uses: Azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            .\devops\Userstory3.2\createconnectedIoTHub.ps1
